project:
  type: website

website:
  title: "Interactive Shiny Dashboard TishLL"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data View"
        href: shiny_app/data_view.qmd
      - text: "Plot View"
        href: shiny_app/plot_view.qmd
